"""Bundle the three deliverable runs into one JS file for the static workbench.

The published demo (docs/debt/) has no Python and no dataroom, so its demo
environment serves these recorded runs instead — the same JSON the pipeline
wrote to final_outputs/, plus the saved chat transcripts split back into
question/answer pairs so the copilot can answer the questions that were
actually asked of it.

Nothing here is synthesised. If a company's run changes, re-run this:

    python3 ui/build_demo_data.py

Companies are fictional; the datarooms that produced these runs are not in
the repo.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT.parent / "docs" / "debt" / "demo-data.js"

# The published bundle carries no client or product name from the original
# engagement. final_outputs/ keeps the deliverable exactly as it was produced;
# only the copy that goes on the public web is scrubbed.
REDACTIONS = [
    (re.compile(r"\bAICA[ _]?Report\b", re.I), "Credit_Report"),
    (re.compile(r"\bAICA\b"), "the assessment"),
]


# Field names carry the client's product name too, and anyone can read the
# bundle. Renamed on the way out; the workbench reads the new name.
KEY_RENAMES = {"aica": "assessment"}


def scrub(value):
    """Walk any JSON value and redact client references in keys and strings."""
    if isinstance(value, str):
        for pattern, replacement in REDACTIONS:
            value = pattern.sub(replacement, value)
        return value
    if isinstance(value, list):
        return [scrub(v) for v in value]
    if isinstance(value, dict):
        return {KEY_RENAMES.get(k, k): scrub(v) for k, v in value.items()}
    return value


def split_transcript(md: str) -> list[dict]:
    """Turn a saved transcript into [{q, a}] pairs.

    The transcript format is `**Underwriter:** …` / `**Copilot:** …`, with a
    `---` rule between turns that belongs to neither speaker.
    """
    turns = []
    # Split on the Underwriter marker, keeping everything after it.
    chunks = re.split(r"\n\*\*Underwriter:\*\*\s*", "\n" + md)
    for chunk in chunks[1:]:
        parts = re.split(r"\n\*\*Copilot:\*\*\s*", chunk, maxsplit=1)
        if len(parts) != 2:
            continue
        question = parts[0].strip()
        answer = parts[1].strip()
        # Drop a trailing horizontal rule left over from the turn separator.
        answer = re.sub(r"\n+---\s*$", "", answer).strip()
        turns.append({"q": question, "a": answer})
    return turns


def main() -> None:
    companies = []
    for n in (1, 2, 3):
        run = json.loads(
            (ROOT / "final_outputs" / f"company_{n}_debt_structure.json").read_text()
        )
        transcript_path = ROOT / "final_outputs" / f"company_{n}_chat_transcript.md"
        turns = split_transcript(transcript_path.read_text()) if transcript_path.exists() else []
        companies.append({"id": f"company_{n}", "run": scrub(run), "turns": scrub(turns)})

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by financial-debt-structuring/ui/build_demo_data.py — do not edit by hand.\n"
        "// Recorded pipeline runs for the demo environment. Companies are fictional.\n"
        "window.DEMO_RUNS = "
        + json.dumps(companies, indent=1, ensure_ascii=False)
        + ";\n"
    )
    total_turns = sum(len(c["turns"]) for c in companies)
    print(f"wrote {OUT.relative_to(ROOT.parent)} — {len(companies)} runs, {total_turns} chat turns")


if __name__ == "__main__":
    main()
